services:
  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-test
    working_dir: /app
    command: poetry run celery -A app.worker worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis-test:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-test:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_GPT_MODEL=${OPENAI_GPT_MODEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}

  fastapi:
    build: .
    container_name: fastapi-test
    working_dir: /app
    command: poetry run pytest --maxfail=1 --disable-warnings
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis-test:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-test:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_GPT_MODEL=${OPENAI_GPT_MODEL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - PYTHONPATH=/app
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
