FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gcc libpq-dev \
    && pip install --upgrade pip \
    && pip install poetry \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-dev --no-root

COPY . .

ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["poetry", "run", "python", "app/worker.py"]
