[tool.poetry]
name = "dv-ai"
version = "0.1.0"
description = "ai server for devterview"
authors = []
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["standard"], version = "^0.115.5"}
pytest = "^8.3.3"
tox = "^4.23.2"
uvicorn = "^0.32.0"
prometheus-fastapi-instrumentator = "^7.0.0"
weave = "^0.51.19"
openai = "^1.54.4"
boto3 = "^1.35.64"
whisper = "^1.1.10"
pydub = "^0.25.1"
httpx = "^0.27.2"
google-cloud-speech = "^2.28.1"
google-cloud-texttospeech = "^2.21.1"
pytest-asyncio = "^0.24.0"
celery = {extras = ["redis"], version = "^5.4.0"}
redis = "^5.2.0"
asyncio = "^3.4.3"
nest-asyncio = "^1.6.0"
asgiref = "^3.8.1"
pytest-docker = "^3.1.1"
pymupdf = "^1.25.1"
python-docx = "^1.1.2"
python-dotenv = "^1.0.1"
pyyaml = "^6.0.2"
requests = "^2.32.3"
pydantic = "^2.10.3"
botocore = "^1.35.81"
tiktoken = "^0.8.0"
<<<<<<< HEAD
<<<<<<< HEAD
elevenlabs = "^1.13.5"
=======
=======
=======
>>>>>>> 0791835 (DV-188 feat: LangChain 적용)
chromadb = "^0.5.20"

>>>>>>> a7cbed7 (DV-188 feat: LLM cache)

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
httpx = "^0.27.2"
tox = "^4.23.2"
watchdog = "^6.0.0"
deptry = "^0.21.1"
<<<<<<< HEAD
<<<<<<< HEAD
black = "^24.10.0"
=======
=======
chromadb = "^0.5.20"
>>>>>>> f3c6170 (DV-188 feat: LLM cache)
>>>>>>> a7cbed7 (DV-188 feat: LLM cache)
=======
chromadb = "^0.5.20"
>>>>>>> 0791835 (DV-188 feat: LangChain 적용)

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
log_cli = true
pythonpath = "app"
addopts = "--tb=short -p no:warnings"
