name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest # 실행할 OS, 여기서는 Ubuntu를 사용

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 코드 체크아웃

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 # 사용할 Python 버전 3.10 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry  # Poetry 설치
          poetry install  # 의존성 설치

      - name: Run linting
        run: |
          poetry run tox -e lint  # Tox로 린트 실행

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 # 사용할 Python 버전 3.10 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run tox -e py310  # Python 3.10 환경에서 테스트 실행
