name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env.test file
        run: |
          echo "CELERY_BROKER_URL=redis://redis-test:6379/0" >> .env.test
          echo "CELERY_RESULT_BACKEND=redis://redis-test:6379/0" >> .env.test
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.test
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> .env.test
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.test
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.test
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.test
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env.test
          echo "ENV=test" >> .env.test
          echo "PYTHONPATH=/app" >> .env.test

      - name: Build and run tests with Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml --env-file .env.test up --build --abort-on-container-exit

      - name: Remove containers
        if: always()
        run: docker compose down
