name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run tests with Docker Compose
        env:
          CELERY_BROKER_URL: redis://redis-test:6379/0
          CELERY_RESULT_BACKEND: redis://redis-test:6379/0
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_GPT_MODEL: ${{ secrets.OPENAI_GPT_MODEL }}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
          ENV: test
          PYTHONPATH: /app
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down
